// SPDX-FileCopyrightText: 2026 Thales Group and the k8s-kms-plugin Contributors
// SPDX-License-Identifier: MIT

// Package cmd implements the k8s-kms-plugin cobra CLI: the root command plus
// the serve, serve rotation, docs, and version subcommands.
package cmd

import (
	"fmt"
	"log/slog"
	"os"
	"time"

	"github.com/lmittmann/tint"
	"github.com/spf13/cobra"

	"github.com/eclipse-keysealer/k8s-kms-plugin/pkg/logging"
)

// cfgFile is the only cobra flag variable the code reads directly: the configuration file has
// to be known before koanf can resolve anything else. Every other flag value is read from the
// per-command structs below, which koanf populates from all four input sources.
var cfgFile string

// RootFlags holds the resolved values of the root command flags. The koanf tags are the long
// flag names, which are also the keys of the k8s-kms-plugin section of the config file.
type RootFlags struct {
	ConfigFile string `koanf:"config"`
	Debug      bool   `koanf:"debug"`
	LogFormat  string `koanf:"log-format"`
	LogLevel   string `koanf:"log-level"`
}

// flagsRoot holds the resolved root command configuration.
var flagsRoot RootFlags

// activeLogLevel is the runtime-adjustable log level shared by all slog handlers.
var activeLogLevel = new(slog.LevelVar)

// rootCmd represents the base command when called without any subcommands
var rootCmd = &cobra.Command{
	Use:   "k8s-kms-plugin",
	Short: "Kubernetes KMS v2 plugin backed by a PKCS #11 TPM or HSM",
	Long: `Connect a Kubernetes cluster to a PKCS #11 TPM or HSM through the Kubernetes KMS v2 API.

kube-apiserver asks the plugin to wrap and unwrap the data encryption key it uses to encrypt
etcd; the key encryption key (KEK) itself never leaves the token, and the plugin never sees a
Secret.

There are two ways to serve, and KEK rotation is one of them:

- "k8s-kms-plugin serve" serves one active KEK.
- "k8s-kms-plugin serve rotation" serves that same active KEK and additionally keeps one
  previous KEK for decryption, so a key rotation runs without downtime.

Reference:

- Project page: https://github.com/eclipse-keysealer/k8s-kms-plugin
- Documentation: https://github.com/eclipse-keysealer/k8s-kms-plugin/tree/master/docs
`,
	// Execute below prints the error once, on stderr. Without this, cobra prints it too.
	SilenceErrors: true,
	// The "Auto generated by spf13/cobra on <date>" footer would otherwise be stamped into
	// every generated markdown page with the date of the run, so `make doc` produced a diff on
	// any day but the one the pages were last committed — which is exactly what the CI
	// freshness check diffs. Inherited by every subcommand through GenMarkdownTree.
	DisableAutoGenTag: true,
	RunE: func(cmd *cobra.Command, _ []string) error {
		slog.Warn("No subcommand provided. Please use one of the available subcommands. Showing help message.")
		return cmd.Help()
	},
}

// silenceUsage stops cobra from answering an error with the whole usage screen. Call it at the
// top of a RunE: everything cobra checks before RunE — flag parsing, required flags, mutually
// exclusive groups — really is a usage mistake and deserves the usage screen, whereas a failure
// inside RunE (an unreachable token, a socket that cannot be bound) is not helped by it and
// only buries the one line that matters.
func silenceUsage(cmd *cobra.Command) {
	cmd.SilenceUsage = true
}

// Execute adds all child commands to the root command and sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the rootCmd.
func Execute() {
	if err := rootCmd.Execute(); err != nil {
		// rootCmd sets SilenceErrors, so this is the only place the error is reported.
		// Errors belong on stderr: stdout carries command output a caller may be piping.
		fmt.Fprintln(os.Stderr, "Error:", err)
		os.Exit(1)
	}
}

func init() {
	// Ensure initConfig runs before anything else
	cobra.OnInitialize(initConfig)

	// Define cobra commands groups
	kmsCmdsGrpMain := &cobra.Group{
		ID:    "kmscmdsgrpmain", // ID needs to be lowercase
		Title: "Main KMS Commands:",
	}

	// Add groups to the root command
	rootCmd.AddGroup(kmsCmdsGrpMain)

	// Flag values are read from the RootFlags struct that koanf populates, so flags are registered
	// without "Flags().*Var" (StringVar, BoolVar, Uint16Var, ...) unless the value is needed before
	// koanf runs, which is only the case for --config.

	// Here you will define your flags and configuration settings.
	// Cobra supports persistent flags, which, if defined here,
	// will be global for your application.
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "",
		"Path to a YAML, TOML or JSON configuration file. Without it, "+
			"k8s-kms-plugin.conf.{yaml,yml,json,toml} is looked up in $HOME and "+
			"$HOME/.config/k8s-kms-plugin/; /etc is never searched.")

	// logging level
	rootCmd.PersistentFlags().Bool("debug", false,
		"Shorthand for --log-level=debug. Mutually exclusive with --log-level.")
	rootCmd.PersistentFlags().String("log-level", "info",
		"Verbosity. One of: trace, debug, info, warn, error, quiet. \"quiet\" silences logging "+
			"entirely. Mutually exclusive with --debug.")
	registerFixedCompletion(rootCmd, "log-level", "trace", "debug", "info", "warn", "error", "quiet")
	rootCmd.PersistentFlags().String("log-format", "text",
		"Log output format. One of: text (coloured, for a terminal), json (for a log collector). "+
			"Logs always go to stderr.")
	registerFixedCompletion(rootCmd, "log-format", "text", "json")
	// A configuration file, not an arbitrary file: complete only the extensions we parse.
	markFlagFilename(rootCmd, "config", configFileExts...)
	rootCmd.MarkFlagsMutuallyExclusive("log-level", "debug") // --log-level and --debug flag are mutually exclusive since debug is an alias for log-level=debug
}

// initConfig loads the configuration file and resolves the root command flags from it, from the
// environment and from the command line. It runs through cobra.OnInitialize, before the
// PersistentPreRunE of the command being executed, so the config file is parsed once and every
// subcommand resolves its own section from it.
func initConfig() {
	// Parse the configuration file, if there is one
	if err := loadConfigFileE(rootCmd); err != nil {
		slog.Error("error reading config file", "error", err)
	}

	// Resolve the root command flags: CLI flags > env vars > config file > defaults
	if _, err := resolveCmdConfigE(rootCmd, &flagsRoot); err != nil {
		slog.Error("error resolving configuration", "cobra_cmd", rootCmd.Name(), "error", err)
	}

	// Determine log level. --debug is an alias for --log-level=debug, and cobra rejects the two
	// being set together, so the resolved value alone decides.
	if flagsRoot.Debug {
		activeLogLevel.Set(slog.LevelDebug)
	} else {
		level, err := logging.ParseLevel(flagsRoot.LogLevel)
		if err != nil {
			slog.Error("unknown log level", "error", err)
		}
		activeLogLevel.Set(level)
		if level == logging.LevelQuiet {
			slog.SetDefault(slog.New(slog.DiscardHandler))
			return
		}
	}

	// Build slog handler based on requested format
	opts := &tint.Options{
		Level:       activeLogLevel,
		TimeFormat:  time.DateTime,
		AddSource:   true,
		ReplaceAttr: logging.ReplaceAttr,
	}
	var handler slog.Handler
	switch flagsRoot.LogFormat {
	case "json":
		handler = slog.NewJSONHandler(os.Stderr, &slog.HandlerOptions{
			Level:       activeLogLevel,
			AddSource:   true,
			ReplaceAttr: logging.ReplaceAttr,
		})
	case "text":
		handler = tint.NewTextHandler(os.Stderr, opts)
	default:
		handler = tint.NewTextHandler(os.Stderr, opts)
		slog.Error("unknown log format", "format", flagsRoot.LogFormat)
	}
	slog.SetDefault(slog.New(handler))

	slog.Debug("log format configured", "log_format", flagsRoot.LogFormat)
	slog.Debug("log level configured", "log_level", flagsRoot.LogLevel)
}
